services:

  backend:
    image: piyushchhakuriya123/my-node-app:1.1
    container_name: task-manager-backend-compose
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: devops-task-manager-frontend:1.0
    container_name: task-manager-frontend-compose
    ports:
      - "5173:4173"
    restart: unless-stopped